In [83]:
import csv
import pandas as pd
import re
import numpy
import matplotlib.pyplot as plt
#import plotly.plotly as py
#import plotly.graph_objs as go
import seaborn as sns

In [5]:
colnames = ['Body','Passengers','Interior','Exterior','Wheels','Tires','Fuel','Basic','Powertrain','Engine','Horsepower',
           'Transmission','Stock','VIN','Year','Make Model','Mileage','Highway','City','Price']
f = open('carsdata1.csv')
df = pd.read_csv('carsdata1.csv',header=None,names=colnames)
f.close()
df.head(1)

,Body,Passengers,Interior,Exterior,Wheels,Tires,Fuel,Basic,Powertrain,Engine,Horsepower,Transmission,Stock,VIN,Year,Make Model,Mileage,Highway,City,Price
0,Sedan,5.0,Candy White,Black,18 Alloy wheels,235 40 tires,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; Expired",3.6L V6,280 hp / 265 ft-lbs. torque,Auto 6-Spd DSG Tptrnc Spt,2.000227e+09,WVWGU7AN7EE505386,2014,Volkswagen CC,"30,795 miles",25\nHWY,17\nCITY,"$21,100"

In [43]:
carscsv1 = open('carsdata3.csv')
g = pd.read_csv('carsdata3.csv',header=None,names=colnames)
carscsv1.close()
carscsv2 = open('carsdata5.csv')
h = pd.read_csv('carsdata5.csv',header=None,names=colnames)
carscsv2.close()
carscsv3 = open('carsdata9am.csv')
i = pd.read_csv('carsdata9am.csv',header=None,names=colnames)
carscsv3.close()
blendeddf = pd.concat([g,h,i], axis=0)
blendeddf.head(2)

,Body,Passengers,Interior,Exterior,Wheels,Tires,Fuel,Basic,Powertrain,Engine,Horsepower,Transmission,Stock,VIN,Year,Make Model,Mileage,Highway,City,Price
https://www.carvana.com/search/2000241154/2014-toyota-xle-minivan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Minivan,7.0,Sandy Beach Metallic,BEIGE,17 Alloy wheels,235 60 tires,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; Expired",3.5L V6,266 hp / 245 ft-lbs. torque,"Automatic, 6-Spd",2.00024e+09,5TDYK3DCXES505633,2014.0,Toyota Sienna,"65,289 miles",25\nHWY,18\nCITY,"$20,700"
https://www.carvana.com/search/2000240357/2017-chrysler-300-limited-sedan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Sedan,5.0,BLACK,BEIGE,18 Alloy wheels,225 60 tires,Gas,"36 mo. / 36,000 mi.; 13 mos. 1,900 mi. left","60 mo. / 60,000 mi.; 37 mos. 25,900 mi. left",Pentastar 3.6L V6,292 hp / 260 ft-lbs. torque,"Automatic, 8-Spd",2.00024e+09,2C3CCAAG7HH596497,2017.0,Chrysler 300,"33,806 miles",30\nHWY,19\nCITY,"$18,600"

In [44]:
blendeddfnana = blendeddf.dropna()
len(blendeddfnana)

1368

In [23]:
#PROCESS FOR THE ENGINE COLUMN = SPLIT BY WHITESPACE
def enginesplit(eng):
    outputlist = eng.split(' ')
    liter = outputlist[0]
    cylinder = outputlist[1]

#PROCESS TO MODIFY THE TIRES COLUMN
def cleantire(a_tire):
    tiresplit = re.findall('\d+',a_tire)
    tirenew = str(tiresplit[0])+'-'+str(tiresplit[1])
    return(tirenew)

def cleanmpg(mpgvalue):
    mpgsplit = re.findall('\d+',mpgvalue)
    mpgsplit = int(mpgsplit[0])
    return(mpgsplit)

#PROCESS HORSEPOWER
def cleanhorse(hp):
    hpsplit = re.findall('\d+',hp)
    return(hpsplit)

#PROCESS TO CLEAN MILEAGE AND PRICE 
def cleanmilesprice(milesorprice):
    cleanvar = re.findall('\d+',milesorprice)
    cleancat = ''
    for i in cleanvar:      
        cleancat = cleancat+i
    cleancat = int(cleancat)
    return(cleancat)

In [65]:
#PROCESS FOR TRANSMISSION COLUMN
def transspeed(trans):
    speed = re.findall('\d+',trans)
    return(speed)

def transtype(trans):
    ttype=''
    match = re.search('auto',trans)
    match1 = re.search('Auto',trans)
    match2 = re.search('manual',trans)
    match3 = re.search('Manual',trans)
    if match or match1:
        ttype = 'auto'
    if match2 or match3:
        ttype = 'manual'
    return(ttype)

In [97]:
df.Engine.dtypes

dtype('O')

In [45]:
#df['A'] = df['A'].map(addOne)
df2 = blendeddfnana
len(df2)
df2.head(3)

,Body,Passengers,Interior,Exterior,Wheels,Tires,Fuel,Basic,Powertrain,Engine,Horsepower,Transmission,Stock,VIN,Year,Make Model,Mileage,Highway,City,Price
https://www.carvana.com/search/2000241154/2014-toyota-xle-minivan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Minivan,7.0,Sandy Beach Metallic,BEIGE,17 Alloy wheels,235 60 tires,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; Expired",3.5L V6,266 hp / 245 ft-lbs. torque,"Automatic, 6-Spd",2.00024e+09,5TDYK3DCXES505633,2014.0,Toyota Sienna,"65,289 miles",25\nHWY,18\nCITY,"$20,700"
https://www.carvana.com/search/2000240357/2017-chrysler-300-limited-sedan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Sedan,5.0,BLACK,BEIGE,18 Alloy wheels,225 60 tires,Gas,"36 mo. / 36,000 mi.; 13 mos. 1,900 mi. left","60 mo. / 60,000 mi.; 37 mos. 25,900 mi. left",Pentastar 3.6L V6,292 hp / 260 ft-lbs. torque,"Automatic, 8-Spd",2.00024e+09,2C3CCAAG7HH596497,2017.0,Chrysler 300,"33,806 miles",30\nHWY,19\nCITY,"$18,600"
https://www.carvana.com/search/2000240548/2016-nissan-s-sport-utility-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Wagon,5.0,Brilliant Silver,Charcoal,17 Alloy wheels,225 65 tires,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; 21 mos. 20,500 mi. left",2.5L I4,170 hp / 175 ft-lbs. torque,"Auto, CVT Xtronic",2.00024e+09,5N1AT2MT2GC743887,2016.0,Nissan Rogue,"39,207 miles",33\nHWY,26\nCITY,"$15,000"

In [46]:
#THIS WILL SPLIT THE MAKE AND MODEL INTO TWO COLUMNS !!
# new data frame with split value columns 
new = df2["Make Model"].str.split(" ", n = 1, expand = True) 
  
# making seperate first name column from new data frame 
df2["Brand"]= new[0] 
  
# making seperate last name column from new data frame 
df2["Model"]= new[1] 
#============================================================================================
#THIS WILL SPLIT THE ENGINE INTO TWO COLUMNS !!
# new data frame with split value columns 
newengine = df2["Engine"].str.split(" ", n = 1, expand = True) 
  
# making seperate first name column from new data frame 
df2["Liters"]= newengine[0] 
  
# making seperate last name column from new data frame 
df2["Cylinder"]= newengine[1] 
df2.head()

/Users/marchass1/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/marchass1/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/marchass1/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/Users/marchass1/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Body,Passengers,Interior,Exterior,Wheels,Tires,Fuel,Basic,Powertrain,Engine,...,Year,Make Model,Mileage,Highway,City,Price,Brand,Model,Liters,Cylinder
https://www.carvana.com/search/2000241154/2014-toyota-xle-minivan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Minivan,7.0,Sandy Beach Metallic,BEIGE,17 Alloy wheels,235 60 tires,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; Expired",3.5L V6,...,2014.0,Toyota Sienna,"65,289 miles",25\nHWY,18\nCITY,"$20,700",Toyota,Sienna,3.5L,V6
https://www.carvana.com/search/2000240357/2017-chrysler-300-limited-sedan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Sedan,5.0,BLACK,BEIGE,18 Alloy wheels,225 60 tires,Gas,"36 mo. / 36,000 mi.; 13 mos. 1,900 mi. left","60 mo. / 60,000 mi.; 37 mos. 25,900 mi. left",Pentastar 3.6L V6,...,2017.0,Chrysler 300,"33,806 miles",30\nHWY,19\nCITY,"$18,600",Chrysler,300,Pentastar,3.6L V6
https://www.carvana.com/search/2000240548/2016-nissan-s-sport-utility-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Wagon,5.0,Brilliant Silver,Charcoal,17 Alloy wheels,225 65 tires,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; 21 mos. 20,500 mi. left",2.5L I4,...,2016.0,Nissan Rogue,"39,207 miles",33\nHWY,26\nCITY,"$15,000",Nissan,Rogue,2.5L,I4
https://www.carvana.com/search/2000239535/2015-ford-sel-wagon-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Wagon,5.0,RED,BLACK,17 Alloy wheels,225 50 tires,Gas/Elec Hybrid,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; Expired",2.0L Hybrid I4,...,2015.0,Ford C-MAX Hybrid,"73,455 miles",47\nHWY,47\nCITY,"$12,600",Ford,C-MAX Hybrid,2.0L,Hybrid I4
https://www.carvana.com/search/2000239921/2016-hyundai-se-sport-utility-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,SUV,7.0,Iron Frost,Gray,18 Alloy wheels,235 60 tires,Gas,"60 mo. / 60,000 mi.; 23 mos. 17,700 mi. left","60 mo. / 60,000 mi.; 23 mos. 17,700 mi. left",3.3L V6,...,2016.0,Hyundai Santa Fe,"42,057 miles",25\nHWY,18\nCITY,"$18,500",Hyundai,Santa Fe,3.3L,V6

In [47]:
#CLEANING PROCESS FOR DF2 -- UNCOMMENT THE LINES TO APPLY
df2.Highway = df2.Highway.map(cleanmpg)#,na_action='ignore')
df2.City = df2.City.map(cleanmpg)
df2.Price = df2.Price.map(cleanmilesprice)
df2.Mileage = df2.Mileage.map(cleanmilesprice)
df2.Tires = df2.Tires.map(cleantire)
df2.head(2)

/Users/marchass1/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3643: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

,Body,Passengers,Interior,Exterior,Wheels,Tires,Fuel,Basic,Powertrain,Engine,...,Year,Make Model,Mileage,Highway,City,Price,Brand,Model,Liters,Cylinder
https://www.carvana.com/search/2000241154/2014-toyota-xle-minivan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Minivan,7.0,Sandy Beach Metallic,BEIGE,17 Alloy wheels,235-60,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; Expired",3.5L V6,...,2014.0,Toyota Sienna,65289,25,18,20700,Toyota,Sienna,3.5L,V6
https://www.carvana.com/search/2000240357/2017-chrysler-300-limited-sedan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Sedan,5.0,BLACK,BEIGE,18 Alloy wheels,225-60,Gas,"36 mo. / 36,000 mi.; 13 mos. 1,900 mi. left","60 mo. / 60,000 mi.; 37 mos. 25,900 mi. left",Pentastar 3.6L V6,...,2017.0,Chrysler 300,33806,30,19,18600,Chrysler,300,Pentastar,3.6L V6

In [61]:
#Split horsepower
newhorse = df2.Horsepower.str.split("/", n = 1, expand = True) 
newhorse.head(3)

#df2['HP'] = newhorse[0].map(cleanmpg) -- > worked.
#df2['Torque'] = newhorse[1].map(cleanmpg)
#newhorse[1]
df2.head(3)

,Body,Passengers,Interior,Exterior,Wheels,Tires,Fuel,Basic,Powertrain,Engine,...,Make Model,Mileage,Highway,City,Price,Brand,Model,Liters,Cylinder,HP
https://www.carvana.com/search/2000241154/2014-toyota-xle-minivan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Minivan,7.0,Sandy Beach Metallic,BEIGE,17 Alloy wheels,235-60,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; Expired",3.5L V6,...,Toyota Sienna,65289,25,18,20700,Toyota,Sienna,3.5L,V6,266
https://www.carvana.com/search/2000240357/2017-chrysler-300-limited-sedan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Sedan,5.0,BLACK,BEIGE,18 Alloy wheels,225-60,Gas,"36 mo. / 36,000 mi.; 13 mos. 1,900 mi. left","60 mo. / 60,000 mi.; 37 mos. 25,900 mi. left",Pentastar 3.6L V6,...,Chrysler 300,33806,30,19,18600,Chrysler,300,Pentastar,3.6L V6,292
https://www.carvana.com/search/2000240548/2016-nissan-s-sport-utility-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n,Wagon,5.0,Brilliant Silver,Charcoal,17 Alloy wheels,225-65,Gas,"36 mo. / 36,000 mi.; Expired","60 mo. / 60,000 mi.; 21 mos. 20,500 mi. left",2.5L I4,...,Nissan Rogue,39207,33,26,15000,Nissan,Rogue,2.5L,I4,170

In [50]:
df2.Horsepower.head(3)

https://www.carvana.com/search/2000241154/2014-toyota-xle-minivan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n            266 hp / 245 ft-lbs. torque
https://www.carvana.com/search/2000240357/2017-chrysler-300-limited-sedan-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n    292 hp / 260 ft-lbs. torque
https://www.carvana.com/search/2000240548/2016-nissan-s-sport-utility-4d-?sri=0eb4eacd-b0c8-42ed-b43d-51cdadeb7ce9\n        170 hp / 175 ft-lbs. torque
Name: Horsepower, dtype: object

In [66]:
#Transmission parse
#tranfast = df2.Transmission.map(transspeed)
#trantype = df2.Transmission.map(transtype)
df2['TransType']= df2.Transmission.map(transtype)

/Users/marchass1/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

IDEAS FOR PLOTTING:
1) Relationships: Mileage and price, brand and price, year and price
2) Value counts: Distribution of year, distribution of price
3) Fuel types - number of Flex Fuel vehicles?
4) Most popular brands
5) Does the type of tire influence price at all?
6) Most

In [76]:
df2.Transmission[1:3]
df2['Year'] = df2['Year'].astype(int)
df3 = df2.copy()

/Users/marchass1/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [135]:
df2.Price.dtype
df2.to_csv('carvanascrapedata.csv')